language: node_js

cache:
  directories:
    - node_modules
    - ~/.npm

node_js:
  - '12'

git:
  depth: 3

script:
  - yarn test

notifications:
  email:
    reciepients:
      - martiniroqueesteban@gmail.com
    on_success: always
    on_failure: always

deploy:
  provide: heroku
  skip-cleanup: true
  keep-history: true
  api_key: $HEROKU_API_KEY # desde heroku
  app:  platzi-store-backend-suichim 
  on:
    repo: SuichiM/platzi-store-backend
